### ISSUE TITLE
Add radiation

### ISSUE THREAD

**Issue by tomdotorg** [glennmckechnie/weewx-mesowx#1]
For those with a solar radiation sensor, would be great to pull it from weewx db and display along with wind.

**Comment by glennmckechnie** [comment]
I'm a bit late to the party with this request. Shockingly so. 
I don't know what happened?

It can be done, The field needs registering in Config.js and config.json. It's then a matter of creating the required chart definition in Config.js.
Not simple, but it is do-able.

If you're still around and running this skin then ?? I'll keep an eye out for it.
