### ISSUE TITLE
php: create_function : Deprecated in php 7.2

### ISSUE THREAD

**Issue by glennmckechnie** [glennmckechnie/weewx-mesowx#3]
create_function in Unit.class.py throws a deprecation warning.

This affects the comps for the stats flag and as a result they don't display (no timestamp is generated for starters)

This is not a big issue at the meoment (unless **;display_errors = On** is set in php.ini, in which case it throws a json breakage) but I'm not having much luck in finding an alternative that works.

https://github.com/glennmckechnie/weewx-mesowx/blob/792fb03dc0c6b8ca13c7cce734a9fd997dcb322a/skins/Mesowx/meso/include/Unit.class.php#L164

**Comment by glennmckechnie** [comment]
Rector suggests the following, and it silently fails, ie: no useful output

        ---------- begin diff ----------
    --- Original 
    +++ New
    @@ -130,7 +130,9 @@
                 $formula = self::$FORMULA[$fromUnit][$toUnit];
                 $functionBody = 'return '. str_replace('#', '$v', $formula) .';';
                 //$fromFunctions[$toUnit] = create_function('$v', $functionBody);
    -           $fromFunctions[$toUnit] = create_function('$v', $functionBody);
    +           $fromFunctions[$toUnit] = function ($v) use ($functionBody) {
    +                eval($functionBody);
    +            };
                 // from rector
                 //$fromFunctions[$toUnit] = function ($v) use ($functionBody) {
                 //    eval($functionBody);
        ----------- end diff -----------

**Comment by rbeerster** [comment]
Here is a diff to correct this issue.  In PHP 8 the create_function function is gone.

```
diff --git a/skins/Mesowx/meso/include/Unit.class.php b/skins/Mesowx/meso/include/Unit.class.php
index 76f547d..ff4099e 100644
--- a/skins/Mesowx/meso/include/Unit.class.php
+++ b/skins/Mesowx/meso/include/Unit.class.php
@@ -161,7 +161,7 @@ class UnitConvert {
         if (!array_key_exists($toUnit, $fromFunctions)) {
             $formula = self::$FORMULA[$fromUnit][$toUnit];
             $functionBody = 'return '. str_replace('#', '$v', $formula) .';';
-            $fromFunctions[$toUnit] = create_function('$v', $functionBody);
+            $fromFunctions[$toUnit] = fn($v) => eval($functionBody);
         }
         return $fromFunctions[$toUnit];
     }
diff --git a/skins/Mesowx/meso/stats.php b/skins/Mesowx/meso/stats.php
index 22bca62..7eb9214 100644
--- a/skins/Mesowx/meso/stats.php
+++ b/skins/Mesowx/meso/stats.php
@@ -60,7 +60,7 @@ if(!$params) {
     exit;
 }
 
-if(!array_key_exists('entityId', $params)) {
+if(!property_exists( $params, 'entityId')) {
     HttpUtil::send400('Must specify an entityId');
     exit;
 }
```

**Comment by glennmckechnie** [comment]
Thank you for this fix.

Apparently I'm stuck at php 7.3 on my dev machine and I get **PHP Parse error: syntax error, unexpected '=>' (T_DOUBLE_ARROW)** because of that old version. (So my long delayed OS upgrade has moved forward - top of the queue in fact.)

While I can't test it at the moment, I've applied it (hopefully without typos). It always needed fixing, and as it appears it's now gone critical, and you have a fix then what can I say but Thank you.

Because this breaks at less than version 8.0, I'll make a note of that requirement on the README. From a security point of view we should probably keep up with the latest anyway and they are pretty clear about what is supported, and are active in dev / security ( https://www.php.net/supported-versions.php )
