### ISSUE TITLE
Thread terminating every day at the same time

### ISSUE THREAD

**Issue by Gitstex** [glennmckechnie/weewx-mesowx#7]
Sep 16 04:12:48 raspberrypi weewx[29364]: sync: unexpected error: [priority,] message string
Sep 16 04:12:48 raspberrypi weewx[29364]:    ****  Traceback (most recent call last):
Sep 16 04:12:48 raspberrypi weewx[29364]:    ****    File "/home/weewx/bin/user/sync.py", line 319, in run
Sep 16 04:12:48 raspberrypi weewx[29364]:    ****      self._run()
Sep 16 04:12:48 raspberrypi weewx[29364]:    ****    File "/home/weewx/bin/user/sync.py", line 405, in _run
Sep 16 04:12:48 raspberrypi weewx[29364]:    ****      self.sync_queued_records()
Sep 16 04:12:48 raspberrypi weewx[29364]:    ****    File "/home/weewx/bin/user/sync.py", line 425, in sync_queued_records
Sep 16 04:12:48 raspberrypi weewx[29364]:    ****      self.post_records(raw_record)
Sep 16 04:12:48 raspberrypi weewx[29364]:    ****    File "/home/weewx/bin/user/sync.py", line 339, in post_records
Sep 16 04:12:48 raspberrypi weewx[29364]:    ****      self.make_http_request(self.update_url, postdata)
Sep 16 04:12:48 raspberrypi weewx[29364]:    ****    File "/home/weewx/bin/user/sync.py", line 350, in make_http_request
Sep 16 04:12:48 raspberrypi weewx[29364]:    ****      (response.status, response.reason, response.data))
Sep 16 04:12:48 raspberrypi weewx[29364]:    ****  TypeError: [priority,] message string
Sep 16 04:12:48 raspberrypi weewx[29364]:    ****  Thread terminating.

**Comment by glennmckechnie** [comment]
Firstly. This is a very old version of this skin - one that predates the current wee_extension version that now uses mesowx.py as its script. (Which handles a non 200 response correctly when accessing data.php ; I just tested that here with weewx4.6.0 and python3.7.3)

However, the sync.py code is still fundamentally the same as mesowx.py so the cause needs to be found.

I really need to see the full, original /home/weewx/bin/user/sync.py script you are running so that I know which version (of the many old ones) we are dealing with. I also need to know which weewx version you are running; which then leads to whether you are using python2.x or python3.
It also helps if I know what if any changes have been made to your setup, a system upgrade?  

Is it an external server you're sending to or an internal (one you have full control of)?
It is failing when it posts an updated record to that server. The code then fails to parse the server response.

It tries to connect to your **remote_server_url**  where it can find the **remote_server_url/updateData.php** script. It cannot connect to the server OR, more likely... It can connect and gets a non typical response back.
When it tries to interpret that response, to create a syslog entry, it all fails miserably as the code cannot decode the response - and we get the error message ... "TypeError: [priority,] message string" ... because it doesn't know how to handle the message.  (python 2 or 3?)

If you are comfortable with editing python scripts then do the following. Backup the existing file then starting at line 349 of the original version...

At line 349, you will comment out lines 349 and 350. You'll then replace them with a simplified single line - which will hopefully omit the offending message strings. Keep any spaces (indentation) the same as the original layout or you'll introduce an error.

                    #syslog.syslog(syslog.LOG_ERR, "sync: http request failed (%s %s): %s" %
                    #              (response.status, response.reason, response.data))
                    syslog.syslog(syslog.LOG_ERR, "sync: http request failed  %s" % response.status)

Restart weewx and make sure it runs with your changes. Wait for it to fail again and send the log extract.

The code returned should be one of the html [status codes](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes) and that information should help us. If it returns nothing (NULL) , that also tells us something: so be verbose!

The server you are connecting to... At the times it fails, what is it doing? recycling logs? down for maintenance? performing routine backups?

**Comment by Gitstex** [comment]
Thank you very much for the reply.

-The version of sync.py is identical to: [lirpa/weewx3/sync.py](https://github.com/glennmckechnie/weewx-mesowx/blob/5b84203fc769a075547eaff054701b382e835312/lirpa/weewx3/sync.py)

-Weewx version: 3.9.2

-The problem started a few months ago without any updates or changes on my part. Every day at the same time: approximately 4:12 am.

-It is an external server that I cannot take full control: www.aruba.it

-I cannot know what the server does in the moment of failure.

Ok i modified the sync.py file. I restarted weewx and it works. Tomorrow I will post the error log. Thank you

**Comment by glennmckechnie** [comment]
python version?

It should be referenced in the first few lines of the weewx syslog file, after it's been started / restarted.

**Comment by Gitstex** [comment]
Python 2.7.3

**Comment by Gitstex** [comment]
Here is the problem log. The error is 502. 
```
Sep 18 04:12:48 raspberrypi weewx[15898]: sync: http request failed  502
Sep 18 04:12:48 raspberrypi weewx[15898]: sync raw: unable to sync record, skipping
Sep 18 04:12:48 raspberrypi weewx[15898]:    ****  Reason: sync: Failed to invoke http://www.flysohigh.net/weather/weewx/oseacco/webmeso/meso/updateData.php after 1 tries
Sep 18 04:12:49 raspberrypi weewx[15898]: sync: http request failed  502
Sep 18 04:12:49 raspberrypi weewx[15898]: sync raw: unable to sync record, skipping
Sep 18 04:12:49 raspberrypi weewx[15898]:    ****  Reason: sync: Failed to invoke http://www.flysohigh.net/weather/weewx/oseacco/webmeso/meso/updateData.php after 1 tries
Sep 18 04:12:50 raspberrypi weewx[15898]: sync: http request failed  502
Sep 18 04:12:50 raspberrypi weewx[15898]: sync raw: unable to sync record, skipping
Sep 18 04:12:50 raspberrypi weewx[15898]:    ****  Reason: sync: Failed to invoke http://www.flysohigh.net/weather/weewx/oseacco/webmeso/meso/updateData.php after 1 tries
```
The most important thing for me, is that he keeps synchronizing after the failure without terminating the Thread. And now it seems to be working correctly! Thank you! 
If there are other attempts that may be useful in solving the problem I am happy to test them

**Comment by glennmckechnie** [comment]
502 Bad Gateway? Hmmm. 
Something that we have no control over, a problem at their end, their server basically vanishes. And always at 4:12 !!
However we do need to handle our end correctly.

How many attempts did it have to cycle through before reconnecting? Hopefully only a short outage.

I've uploaded a modified sync.py file to the repo lirpa/weewx3/sync.py (version sync_lhgm10.py). It incorporates the change we discussed above, it also adds a check for a missing server / no route problem, along with a few tweaks to satisfy the syntax checker.

Can you test this script for me and see that it works for you. Do it at a time that suits you - there is no rush.
You can test the missing server / no route check by putting an invalid url in your weewx.conf file. It should log that failure and weewx will continue to run as normal when it will try the next mesowx loop/archive packet and log that outcome as well. 
Correct the dud url and restart weewx and you will be back in business.
If you can run the script for 24 hours ie:- through one of your failure times, that would be the best test of all.

I cannot fully check it here as I don't have a server configured for the old setup. I've done a rudimentary python2.7 check but the true proof lies at your end.

I've modified the newest mesowx.py with similar changes and have pushed that to the master repo.

If you ever feel the need to upgrade your weewx to version 4 then give that latest release a go. It should be a breeze to setup. (Compared to the old days!)  But then if it ain't broke... why change ! :-)

**Comment by Gitstex** [comment]
`How many attempts did it have to cycle through before reconnecting? Hopefully only a short outage.`
Yes, just a short break. I have only one error and I think I am losing only one LOOP packet. Definitely less than 10 seconds.

Ok I installed the new sync.py file and tried to put an invalid url and restart weewx. Weewx is terminated immediately. Here is the log:

Sep 24 15:59:07 raspberrypi weewx[11587]: sync archive: http request failed  404
Sep 24 15:59:07 raspberrypi weewx[11587]: engine: Caught unrecoverable exception in engine:
Sep 24 15:59:07 raspberrypi weewx[11587]:     ****  sync archive: Request to http://www.flysohigh.net/data.php failed, server returned 404 status with reason 'Not Found'. Is the url correct?
Sep 24 15:59:07 raspberrypi weewx[11587]:     ****  Traceback (most recent call last):
Sep 24 15:59:07 raspberrypi weewx[11587]:     ****    File "/home/weewx/bin/weewx/engine.py", line 888, in main
Sep 24 15:59:07 raspberrypi weewx[11587]:     ****      engine = engine_class(config_dict)
Sep 24 15:59:07 raspberrypi weewx[11587]:     ****    File "/home/weewx/bin/weewx/engine.py", line 78, in __init__
Sep 24 15:59:07 raspberrypi weewx[11587]:     ****      self.loadServices(config_dict)
Sep 24 15:59:07 raspberrypi weewx[11587]:     ****    File "/home/weewx/bin/weewx/engine.py", line 142, in loadServices
Sep 24 15:59:07 raspberrypi weewx[11587]:     ****      self.service_obj.append(weeutil.weeutil._get_object(svc)(self, config_dict))
Sep 24 15:59:07 raspberrypi weewx[11587]:     ****    File "/home/weewx/bin/user/sync.py", line 124, in __init__
Sep 24 15:59:07 raspberrypi weewx[11587]:     ****      self.back_fill()
Sep 24 15:59:07 raspberrypi weewx[11587]:     ****    File "/home/weewx/bin/user/sync.py", line 189, in back_fill
Sep 24 15:59:07 raspberrypi weewx[11587]:     ****      last_datetime_synced = self.fetch_latest_remote_datetime()
Sep 24 15:59:07 raspberrypi weewx[11587]:     ****    File "/home/weewx/bin/user/sync.py", line 241, in fetch_latest_remote_datetime
Sep 24 15:59:07 raspberrypi weewx[11587]:     ****      http_response = self.make_http_request(self.latest_url, postdata)
Sep 24 15:59:07 raspberrypi weewx[11587]:     ****    File "/home/weewx/bin/user/sync.py", line 286, in make_http_request
Sep 24 15:59:07 raspberrypi weewx[11587]:     ****      raise FatalSyncError (message)
Sep 24 15:59:07 raspberrypi weewx[11587]:     ****  FatalSyncError: sync archive: Request to http://www.flysohigh.net/data.php failed, server returned 404 status with reason 'Not Found'. Is the url correct?
Sep 24 15:59:07 raspberrypi weewx[11587]:     ****  Exiting.

Now I have put back the correct link, restarted weewx and everything works fine. 
Tomorrow I will post the log of what happens at 4:12 AM with the new sync.py

**Comment by Gitstex** [comment]
Here is the log with the new sync.py
Everything works perfectly. 
Thank you very much!
```
Sep 25 04:12:05 raspberrypi weewx[15217]: sync: http request failed 502
Sep 25 04:12:05 raspberrypi weewx[15217]: sync raw: unable to sync record, skipping
Sep 25 04:12:05 raspberrypi weewx[15217]:    ****  Reason: sync: Failed to invoke http://www.flysohigh.net/weather/weewx/oseacco/webmeso/meso/updateData.php after 1 tries
Sep 25 04:12:08 raspberrypi weewx[15217]: sync: http request failed 502
Sep 25 04:12:08 raspberrypi weewx[15217]: sync raw: unable to sync record, skipping
Sep 25 04:12:08 raspberrypi weewx[15217]:    ****  Reason: sync: Failed to invoke http://www.flysohigh.net/weather/weewx/oseacco/webmeso/meso/updateData.php after 1 tries
Sep 25 04:12:09 raspberrypi weewx[15217]: sync: http request failed 502
Sep 25 04:12:09 raspberrypi weewx[15217]: sync raw: unable to sync record, skipping
Sep 25 04:12:09 raspberrypi weewx[15217]:    ****  Reason: sync: Failed to invoke http://www.flysohigh.net/weather/weewx/oseacco/webmeso/meso/updateData.php after 1 tries
```

**Comment by glennmckechnie** [comment]
Excellent.
